### ISSUE TITLE
Random reboot on Dipper (Xiaomi Mi8)

### ISSUE THREAD

**Issue by Goldweavers** [ethan-halsall/Simple-Kernel#1]
I'm encountering random reboot/shutdown. I have tried to determine the cause but without success.

This seem to happend little bit after I switch off the screen or maybe when the phone is exiting stand-by mode.

ROM: MIUI by xiaomi.eu 10.3.1.0 (PEACNXM)
Kernel: 4.9.169-Simple-3.35-g34726426

**Comment by ethan-halsall** [comment]
I am aware of this issue, but I cannot replicate it think, does it only occur on fingerprint input, or whenever the display is woken?

**Comment by ethan-halsall** [comment]
I am pretty sure this has been resolved

**Comment by ethan-halsall** [comment]
Fixed and will be in next update

**Comment by Goldweavers** [comment]
It never happened when the display was on, only in waking up step. For fingerprint input, it has ocurred one or two times but it mostly happend in stand-by mode.

In the other hand, my phone most commonly was shutting down, not rebooting.

I cannot help you more with logs or something else because I removed your kernel for this reason.
