### ISSUE TITLE
FC for MIUI Camera or Google cam

### ISSUE THREAD

**Issue by Acid-miuipolskapl** [ethan-halsall/Simple-Kernel#7]
Hi
All your kernel version for dipper have FC for MIUI Camera or Google cam.
This bug is since few versions in the past and also with current. 
Tested on xiaomi.eu dev versions. 

Log: [http://dpaste.com/0VD6QQN](url)

Probably this is the reason:
`java.io.FileNotFoundException: /proc/8785/task/8785/top_app: open failed: ENOENT (No such file or directory)`

**Comment by ethan-halsall** [comment]
This kernel is for android open source roms only, miui is not supported

**Comment by Acid-miuipolskapl** [comment]
Why? This kernel works fine for MIUI roms, as most MI 8 users use MIUI and not aosp.
Only camera is broken. You don't know how to do it? Then why other kernel makes cope with camera and it works fine?
